array:
	gcc tArray.c -pedantic -Wall -Wextra -Wfloat-equal -std=c90 -lm
	./a.out
a2:
	gcc tArray2.c -pedantic -Wall -Wextra -Wfloat-equal -std=c90 -lm
	./a.out
list:
	gcc importListFromFile.c -o importListFromFile -pedantic -Wall -Wextra -Wfloat-equal -std=c90
