pla:
	gcc planTrium.c -o plan.out -pedantic -Wall -Wextra -Wfloat-equal -std=c90 -lm
	./plan.out
vid:
	gcc VideoPlus.c -VideoPlus.out -pedantic -Wall -Wextra -Wfloat-equal -std=c90 -lm
	./VideoPlus.out
hai:
	gcc HSeq.c -o Hseq.out -pedantic -Wall -Wextra -Wfloat-equal -std=c90 -lm
	./Hseq.out
mon:
	gcc MCarlo.c -o MCarlo.out -pedantic -Wall -Wextra -Wfloat-equal -std=c90 -lm
	./MCarlo.out
mic:
	gcc Micro.c -o Micro.out -pedantic -Wall -Wextra -Wfloat-equal -std=c90 -lm
	./Micro.out
play:
	gcc Play.c -o Play.out -pedantic -Wall -Wextra -Wfloat-equal -std=c90 -lm
	./Play.out
p2:
	gcc Play2.c -o Play2.out -pedantic -Wall -Wextra -Wfloat-equal -std=c90 -lm
	./Play2.out
R101:
		gcc Rule101Synt-Array.c -o Rule101SA.out -pedantic -Wall -Wextra -Wfloat-equal -std=c90 -lm
		./Rule101SA.out
