compile:
	gcc -pedantic -Wall -Wextra -std=c90 lifewar.c -o lifewar.out
war2:
	./lifewar.out best1.lif best2.lif 2
war20:
	./lifewar.out best1.lif best2.lif 20
war3:
	./lifewar.out best3.lif best4.lif 3
war30:
	./lifewar.out best3.lif best4.lif 30
compileRand:
	gcc -pedantic -Wall -Wextra -std=c90 WlifeScript.c -o wScript.out
compileRect:
	gcc -pedantic -Wall -Wextra -std=c90 WScript.c -o wScript.out
best1:
	./wScript.out best1.lif
	./wScript.out best2.lif
best3:
	./wScript.out best3.lif
	./wScript.out best4.lif
