compile:
	gcc -pedantic -Wall -Wextra -std=c90 GOL.c -o GOL.out
war2:
	./GOL.out best1.lif best2.lif 2
war20:
	./GOL.out best1.lif best2.lif 20
war3:
	./GOL.out best3.lif best3.lif 3
war30:
	./GOL.out best3.lif best4.lif 30
glider:
	./GOL.out glider1.lif glider1.lif 200
gliderS:
	./GOL.out glider1.lif gliderdl.lif 2
compileRand:
	gcc -pedantic -Wall -Wextra -std=c90 WlifeScript.c -o wScript.out
compileRect:
	gcc -pedantic -Wall -Wextra -std=c90 WScript.c -o wScript.out
best1:
	./wScript.out best1.lif
	./wScript.out best2.lif
best3:
	./wScript.out best3.lif
	./wScript.out best4.lif
